name: smalltalkCI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # DEBUG
      matrix:
        os: [ ubuntu-latest ]
        smalltalk: [ Squeak64-Trunk ]
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Unpack tdlib test database
        shell: bash
        run: |
          ./.github/scripts/decrypt.sh assets/tests/tdlib.zip.gpg
          unzip assets/tests/tdlib.zip
        env:
          TB_TEST_ASSET_PASSPHRASE: ${{ secrets.TB_TEST_ASSET_PASSPHRASE }}
      - name: Turnstyle (critical section)
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run test suite
        shell: bash
        run: smalltalkci -s ${{ matrix.smalltalk }}
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # for coverage reports
          TB_TEST_BOT_TOKEN: ${{ secrets.TB_TEST_BOT_TOKEN }}
          TB_TEST_CLIENT_CHAT_ID: ${{ secrets.TB_TEST_CLIENT_CHAT_ID }}
          TB_TEST_BOT_CHAT_ID: ${{ secrets.TB_TEST_BOT_CHAT_ID }}
      - name: Send email on failure
        #debug#if: ${{ github.event_name == 'schedule' && failure() }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: GitHub CI failed for ${{ github.repository }}
          body: Build job of ${{ github.repository }} failed! See https://github.com/${{ github.repository }}/runs/${{ github.run_id }} for more information.
          to: ${{ secrets.MAIL_RECEIVER }}
          from: GitHub CI
